use_frameworks!

def PodTest1
end

target 'MachLib_Example' do
  pod 'MachLib', :path => '../'

  target 'MachLib_Tests' do
    inherit! :search_paths

    
  end
end



#其他项目引用：
#platform :ios, '9.0'
#
#source 'https://github.com/housl/MachRepos.git'
#source 'https://github.com/CocoaPods/Specs.git’
#
#target 'CarPrice' do
#    #    pod 'MachLib'
#    pod 'MachLib', :path => '/Users/machou/gitDir/MachLib/'
#end
